name: Environment Deployment 
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "image tag"
        required: true
  repository_dispatch:
  # push:
jobs:
  setup_kustomize:
    runs-on: ubuntu-latest
    name: setting Kustomize
    steps:
      - name: install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
  deploy_to_dev:
    runs-on: ubuntu-latest
    name: Deploying to development environment
    environment: dev
    needs: [setup_kustomize]
    steps:
      - uses: actions/checkout@v2
      - name: Dev manual deployment
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo deploying to dev environment...!!!
          echo $PATH
          git config --global user.name "Jarvis"
          git config --global user.email "jarvis@starkindustries.com"
          pushd envs/overlay/dev
          kustomize edit set image nginx:'${{ github.event.inputs.image_tag }}'
          popd
          git add .
          git commit -m "Image updated"
          git push
      - uses: actions/checkout@v2
      - name: Dev workflow deployment
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo deploying to dev environment...!!!
          git config --global user.name "Jarvis"
          git config --global user.email "jarvis@starkindustries.com"
          pushd envs/overlay/dev
          kustomize edit set image nginx:'${{ github.event.client_payload.image_tag }}'
          popd
          git add .
          git commit -m "Image updated"
          git push
  deploy_to_stage:
    runs-on: ubuntu-latest
    name: Deploying to staging environment
    environment: stage
    needs: [deploy_to_dev]
    steps:
      - name: Staging deployment 
        run: echo deploying to stage environment...!!!
  deploy_to_prod:
    runs-on: ubuntu-latest
    name: Deploying to prod environment
    environment: prod
    needs: [deploy_to_stage]
    steps:
      - name: Production deployment 
        run: echo deploying to prod environment...!!!