name: Environment Deployment 
on:
  push:
jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    name: Deploying to development environment
    environment: dev
    steps:
      - name: Dev deployment 
        run: echo deploying to dev environment...!!!
  deploy_to_stage:
    runs-on: ubuntu-latest
    name: Deploying to staging environment
    environment: stage
    needs: [deploy_to_dev]
    steps:
      - name: Staging deployment 
        run: echo deploying to stage environment...!!!
  deploy_to_prod:
    runs-on: ubuntu-latest
    name: Deploying to prod environment
    environment: prod
    needs: [deploy_to_stage]
    steps:
      - name: Production deployment 
        run: echo deploying to prod environment...!!!