name: Environment Deployment 
on:
  push:
jobs:
  setup_kustomize:
    runs-on: ubuntu-latest
    name: setting Kustomize
    steps:
      - name: install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
  deploy_to_dev:
    runs-on: ubuntu-latest
    name: Deploying to development environment
    environment: dev
    needs: [setup_kustomize]
    steps:
      - name: Dev deployment 
        run: |
          echo deploying to dev environment...!!!
          kustomize version
          pwd
          ls -al
          pushd envs/overlay/dev
          pwd
          kustomize edit set image nginx:1.0.2
          cat kustomization.yaml
          popd
          pwd
  deploy_to_stage:
    runs-on: ubuntu-latest
    name: Deploying to staging environment
    environment: stage
    needs: [deploy_to_dev]
    steps:
      - name: Staging deployment 
        run: echo deploying to stage environment...!!!
  deploy_to_prod:
    runs-on: ubuntu-latest
    name: Deploying to prod environment
    environment: prod
    needs: [deploy_to_stage]
    steps:
      - name: Production deployment 
        run: echo deploying to prod environment...!!!