name: Environment Deployment 
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "image tag"
        required: true
  repository_dispatch:
  # push:
jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    name: Deploying to development environment
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Dev manual deployment
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: arunalakmal/kustomize_actions@main
        with:
          bot_name: "Jarvis"
          path: "envs/overlay/dev"
          image: "nginx"
          event_type: '${{ github.event.inputs.image_tag }}'
          version: "v4.5.7"
      - name: Dev workflow deployment
        if: ${{ github.event_name == 'repository_dispatch' }}
        uses: arunalakmal/kustomize_actions@main
        with:
          bot_name: "Jarvis"
          path: "envs/overlay/dev"
          image: "nginx"
          event_type: '${{ github.event.client_payload.image_tag }}'
          version: "v4.5.7"
  deploy_to_stage:
    runs-on: ubuntu-latest
    name: Deploying to staging environment
    environment: stage
    needs: [deploy_to_dev]
    steps:
      - uses: actions/checkout@v2
      - name: Staging manual deployment 
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: arunalakmal/kustomize_actions@main
        with:
          bot_name: "Jarvis"
          path: "envs/overlay/stage"
          image: "nginx"
          event_type: '${{ github.event.inputs.image_tag }}'
          version: "v4.5.7"
      - name: Dev workflow deployment
        if: ${{ github.event_name == 'repository_dispatch' }}
        uses: arunalakmal/kustomize_actions@main
        with:
          bot_name: "Jarvis"
          path: "envs/overlay/stage"
          image: "nginx"
          event_type: '${{ github.event.client_payload.image_tag }}'
          version: "v4.5.7"
  deploy_to_prod:
    runs-on: ubuntu-latest
    name: Deploying to prod environment
    environment: prod
    needs: [deploy_to_stage]
    steps:
      - uses: actions/checkout@v2
      - name: Production manual deployment 
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: arunalakmal/kustomize_actions@main
        with:
          bot_name: "Jarvis"
          path: "envs/overlay/prod"
          image: "nginx"
          event_type: '${{ github.event.inputs.image_tag }}'
          version: "v4.5.7"
      - name: Prodution workflow deployment
        if: ${{ github.event_name == 'repository_dispatch' }}
        uses: arunalakmal/kustomize_actions@main
        with:
          bot_name: "Jarvis"
          path: "envs/overlay/prod"
          image: "nginx"
          event_type: '${{ github.event.client_payload.image_tag }}'
          version: "v4.5.7"